= Asciidoctor presentation framework
:source-highlighter: pygments
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :bangbang:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

*Provides Reveal.js backend for asciidoc presentations.*

== Configuration

* `SLIDES_PATH` - path to directory inside container with .adoc sources. Default value: _/documents/slides_ 
* `RESOURCES_PATH` - path to directory inside container contains css, images and all other resources. 
Default value: _${SLIDES_PATH}/resources_
* `TARGET_PATH` - path to directory inside container with compiled slides. Default value: _/target_

[IMPORTANT]
====
Default configuration assumes directory hierarchy:

* `<PATH_TO_MAIN_DIR>/slides` - folder with asciidoc sources
* `<PATH_TO_MAIN_DIR>/slides/resources` - folder with addtional resources such as custom css, images, etc
====

== Run it

.Run with default config
[source,bash]
----
docker run -it -p 80:80 -v <PATH_TO_MAIN_DIR>:/documents/ wiktorsztajerowski/asciidoc-presenter:latest
----

Now go to `http://localhost` and enjoy your presentation :)

NOTE: HTML files are names same as source files, so if you have `slides.adoc` you find your slides on 
`http://localhost/slides.html`

TIP: check container output - it lists the serving files.

== Customize run

.Provide custom slides source
[source,bash]
----
docker run -it -p 80:80 -v <PATH_TO_MAIN_DIR>:/documents/ -e SLIDES_PATH=/documents/custom/path/slides wiktorsztajerowski/asciidoc-presenter:latest
----

.Provide custom resource path
[source,bash]
----
docker run -it -p 80:80 -v <PATH_TO_MAIN_DIR>:/documents/ -e RESOURCES_PATH=/documents/custom/path/to/resources wiktorsztajerowski/asciidoc-presenter:latest
----

.Getting generates slides
[source,bash]
----
docker run -it -p 80:80 -v <PATH_TO_MAIN_DIR>:/documents/  -v <PATH_TO_TARGET_DIR>:/target wiktorsztajerowski/asciidoc-presenter:latest
----

.Provide custom target path
[source,bash]
----
docker run -it -p 80:80 -v <PATH_TO_MAIN_DIR>:/documents/  -v <PATH_TO_TARGET_DIR>:/custom/target -e TARGET_PATH=/custom/target wiktorsztajerowski/asciidoc-presenter:latest
----

=== Acknowledgments

Many thanks to the AsciiDoctor team for providing https://github.com/asciidoctor/docker-asciidoctor[AsciiDoctor Docker Image], which I used as a base for this image.

